# Generated by Django 4.1.1 on 2024-06-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('loan_start_purchase_date', models.DateField()),
                ('classification', models.CharField(max_length=100)),
                ('funding_institution', models.CharField(max_length=100)),
                ('loan_ref_number', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
