# Generated by Django 5.0.2 on 2024-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_register', '0002_asset_financingdetails_purchasedetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingdetails',
            name='installments',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='cost_price',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='disc_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
